#!/bin/bash

# will stop this script on any error
set -e

venv="venv"

CC='\033[0;35m'
OC='\033[0;33m'
GC='\033[0;32m'
RC='\033[0;31m'
NC='\033[0m'

usage()
{
	echo "Syntax: run.sh [ -h ] [ -r ] [ -k ]"
	echo "Options:"
	echo ""
	echo "   -h          Show this help and exit."
	echo "   -i          Install venv if it does not exist and exit."
	echo "   -r          Force reinstall venv and exit unless -d argument is specified."
	echo
	echo "Examples:"
	echo
	echo "   ./run -i"
	echo "   ./run -r"
}

while getopts "hri" option; do
	case $option in
		h)
			usage
			exit 0;;
		i)
			install=y
			;;
		r)
			reinstall=y
			;;
		\?)
			echo "error: invalid argument given, run with -h"
			exit 1;;
		esac
done

if [ -v reinstall ]; then
	echo -e "${OC}Removing $venv...${NC}"
	rm -rf $venv
fi

if [ ! -d $venv ]; then
	echo -e "${OC}Preparing $venv...${NC}"
	python3 -m venv $venv
	source $venv/bin/activate
	pip install -U pip wheel setuptools
	pip install -r requirements.txt
else
	source $venv/bin/activate
fi